import { Character, Vocation } from '../types';

export const DEMO_CHARACTERS: Array<
  Omit<Character, 'id' | 'ownerId' | 'ownerEmail' | 'minShareLevel' | 'maxShareLevel' | 'createdAt' | 'updatedAt'>
> = [
  {
    characterName: 'Lord Blaker',
    level: 450,
    vocation: 'Knight' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['das 20h - 23h', 'Noite (18h - 00h)'],
    availableDays: ['Segunda', 'Quarta', 'Sexta', 'Sábado', 'Domingo'],
    huntsInterest: ['Soul War - Crater', 'Library - Fire Section', 'Nagás - Temple / Coastal'],
    bestiaryStatus: 'Já tem Bestiary feito • Charms full (Dodge, Zap, Freeze, Wound, Low Blow)',
    interestedInProposals: true,
    whatsappNumber: '+55 11 98888-1234',
  },
  {
    characterName: 'Ailura Moonwhisper',
    level: 430,
    vocation: 'Druid' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['das 20h - 23h'],
    availableDays: ['Terça', 'Quinta', 'Sexta', 'Sábado'],
    huntsInterest: ['Soul War - Crater', 'Library - Ice Section', 'Buried Cathedral -3'],
    bestiaryStatus: 'Precisa de Bestiary • Faltam 200 mobs de crater, charms Freeze e Curse',
    interestedInProposals: true,
    whatsappNumber: '+55 19 99777-5678',
  },
  {
    characterName: 'Ignis Pyroclast',
    level: 460,
    vocation: 'Sorcerer' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['Noite (18h - 00h)', 'das 19h - 22h'],
    availableDays: ['Segunda', 'Quarta', 'Sexta', 'Sábado'],
    huntsInterest: ['Soul War - Crater', 'Library - Fire Section', 'Rotten Blood - Bakragore'],
    bestiaryStatus: 'Precisa de Bestiary • Foco em desbloquear Criaturas Raras e Charms',
    interestedInProposals: true,
    whatsappNumber: '+55 31 99666-4321',
  },
  {
    characterName: 'Silent Fletcher',
    level: 440,
    vocation: 'Paladin' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['das 20h - 23h', 'Madrugada (00h - 06h)'],
    availableDays: ['Segunda', 'Terça', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
    huntsInterest: ['Library - Energy Section', 'Nagás - Temple / Coastal', 'Issavi - Sphinx & Goannas'],
    bestiaryStatus: 'Já tem Bestiary feito • Diamond Arrows e Charms Holy/Zap prontos',
    interestedInProposals: true,
    whatsappNumber: '+55 41 99555-8765',
  },
  {
    characterName: 'Master Kenshin',
    level: 420,
    vocation: 'Monk' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['das 21h - 00h', 'Noite (18h - 00h)'],
    availableDays: ['Sexta', 'Sábado', 'Domingo'],
    huntsInterest: ['Soul War - Crater', 'Bullita - Ingol', 'Cobalt Cathedral'],
    bestiaryStatus: 'Precisa de Bestiary • Farmando charms defensivos para 5-man PT',
    interestedInProposals: true,
    whatsappNumber: '+55 21 99444-9876',
  },
  {
    characterName: 'Thais Vanguard',
    level: 280,
    vocation: 'Knight' as Vocation,
    world: 'Kalibra',
    availablePeriods: ['das 19h - 22h', 'Tarde (12h - 18h)'],
    availableDays: ['Segunda', 'Quarta', 'Sexta'],
    huntsInterest: ['Asura Palace & Vaults', 'Gazer Spectres', 'Buried Cathedral -3'],
    bestiaryStatus: 'Precisa de Bestiary • Foco total em pegar primeiros 2000 Charm Points',
    interestedInProposals: true,
    whatsappNumber: '+55 11 99111-2233',
  },
];
